### ISSUE TITLE
Doesn't detect if dividers added dynamically to scope

### ISSUE THREAD

**Issue by kpowerinfinity** [Poordeveloper/ion-sticky#1]
Hello,

Thank you for this! This is terrific and I am planning to use it my project. One issue I am facing is that the dividers are not auto-detected during scope change. I am dynamically inserting the list based on what the user selects, so it doesn't add them to the dividers[] array.

I can possibly write a scope watch, but I am a little unsure about the performance impact, so thought of asking you directly!

Cheers, Krishna.

**Comment by Poordeveloper** [comment]
On 06/01/2015 01:37 PM, Krishna Mehra wrote:
>
> Hello,
>
> Thank you for this! This is terrific and I am planning to use it my 
> project. One issue I am facing is that the dividers are not 
> auto-detected during scope change. I am dynamically inserting the list 
> based on what the user selects, so it doesn't add them to the 
> dividers[] array.
>
> I can possibly write a scope watch, but I am a little unsure about the 
> performance impact, so thought of asking you directly!
>
> Cheers, Krishna.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Poordeveloper/ion-sticky/issues/1>.
>
Can you make a codepen for this issue? I will add a fix in.

Thanks.

**Comment by Poordeveloper** [comment]
I just added a fix, moved dividers creation to scroll event callback. In my demo, it adds 0.41699991561472416 millisecond measured with performance.now() on my Desktop. Let me know if you have better idea. Thanks.

**Comment by Poordeveloper** [comment]
I just made another test with 1800+ items and 170+ dividers, on average, it adds in 0.5 millisecond. So I think this solution is quite scalable.

**Comment by kpowerinfinity** [comment]
Thank you. I am going to check this out and get back to you! Thanks a ton!

**Comment by Poordeveloper** [comment]
If you have no problem, I will close this issue. Thanks.

**Comment by kpowerinfinity** [comment]
Thanks!
