### ISSUE TITLE
<select> in divider doesn't work correctly

### ISSUE THREAD

**Issue by ndrake** [Poordeveloper/ion-sticky#2]
I'm trying to have a divider include an HTML select box. When I select an option (other than the first item) and then scroll, the select reverts back to the initial option. If you scroll back to the top of the list, the select changes back to what it should have been set to.

Here is a code pen displaying the issue:

http://codepen.io/anon/pen/bdvjyq

**Comment by Poordeveloper** [comment]
fixed, please check out 1.0.3
