### ISSUE TITLE
Anchorscroll goes to far 

### ISSUE THREAD

**Issue by MisterJack49** [Poordeveloper/ion-sticky#3]
Hi,
When I do $ionicScrollDelegate.anchorScroll.

    $scope.goToday = function(){
       $location.hash('today-true');
       $ionicScrollDelegate.anchorScroll(true);
    };

it goes to far, the item stops below the header, not below the divider.
![57966257d0c36b141f4ffc3e65a93586f73573d2 1](https://cloud.githubusercontent.com/assets/9714069/8618620/32957586-2710-11e5-9dd4-70fa1b5c7934.png)

**Comment by Poordeveloper** [comment]
can you create a code pen for this issue?

**Comment by Poordeveloper** [comment]
BTW, I can not see it is an issue related to ion-sticky which only clones the divider and show it on top.

**Comment by MisterJack49** [comment]
http://codepen.io/MisterJack49/pen/MwwJoy/

**Comment by Poordeveloper** [comment]
I can not see diff with ion-affix or without ion-affix for your pen.

**Comment by hws1124** [comment]
when use collection-repeat, scrolling ,and then sticky header will hide,because  with collection-repeat,the divider item which you can not see will auto be removed by DOM,
Can you resolve this problem? and give a code pen.

demo-collection-repeat.html have this problem,scrolling, and sticky header be hided

**Comment by Poordeveloper** [comment]
Sorry, this can not work with collection-repeat which will introduce big change and make it not easy to use.

**Comment by Poordeveloper** [comment]
I have a private implementation working with collection-repeat, if you have interest, I can share with u.

**Comment by Poordeveloper** [comment]
https://gist.github.com/Poordeveloper/e6a1714ea399f95c779f
