### ISSUE TITLE
[Feature] Custom Style for stiky divider

### ISSUE THREAD

**Issue by Carniatto** [Poordeveloper/ion-sticky#5]
Thanks for the extension,

I would like to request the configuration for color when the item-divider is sticky.

Can I make a pull request for this?

Thanks

**Comment by Poordeveloper** [comment]
Yes, Please

**Comment by Carniatto** [comment]
Submitted a pull request for fixing it #7

**Comment by Poordeveloper** [comment]
Thank, Merged

**Comment by Carniatto** [comment]
Can you make a release for this?

**Comment by Poordeveloper** [comment]
Created
